services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
    - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl","-f" ,"http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
  scraper:
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    environment:
    - OLLAMA_HOST=http://localhost:11434
volumes:
  ollama_data: